require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GetGuidsController do

  # This should return the minimal set of attributes required to create a valid
  # GetGuid. As you add validations to GetGuid, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GetGuidsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all get_guids as @get_guids" do
      get_guid = GetGuid.create! valid_attributes
      get :index, {}, valid_session
      assigns(:get_guids).should eq([get_guid])
    end
  end

  describe "GET show" do
    it "assigns the requested get_guid as @get_guid" do
      get_guid = GetGuid.create! valid_attributes
      get :show, {:id => get_guid.to_param}, valid_session
      assigns(:get_guid).should eq(get_guid)
    end
  end

  describe "GET new" do
    it "assigns a new get_guid as @get_guid" do
      get :new, {}, valid_session
      assigns(:get_guid).should be_a_new(GetGuid)
    end
  end

  describe "GET edit" do
    it "assigns the requested get_guid as @get_guid" do
      get_guid = GetGuid.create! valid_attributes
      get :edit, {:id => get_guid.to_param}, valid_session
      assigns(:get_guid).should eq(get_guid)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GetGuid" do
        expect {
          post :create, {:get_guid => valid_attributes}, valid_session
        }.to change(GetGuid, :count).by(1)
      end

      it "assigns a newly created get_guid as @get_guid" do
        post :create, {:get_guid => valid_attributes}, valid_session
        assigns(:get_guid).should be_a(GetGuid)
        assigns(:get_guid).should be_persisted
      end

      it "redirects to the created get_guid" do
        post :create, {:get_guid => valid_attributes}, valid_session
        response.should redirect_to(GetGuid.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved get_guid as @get_guid" do
        # Trigger the behavior that occurs when invalid params are submitted
        GetGuid.any_instance.stub(:save).and_return(false)
        post :create, {:get_guid => {  }}, valid_session
        assigns(:get_guid).should be_a_new(GetGuid)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GetGuid.any_instance.stub(:save).and_return(false)
        post :create, {:get_guid => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested get_guid" do
        get_guid = GetGuid.create! valid_attributes
        # Assuming there are no other get_guids in the database, this
        # specifies that the GetGuid created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GetGuid.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => get_guid.to_param, :get_guid => { "these" => "params" }}, valid_session
      end

      it "assigns the requested get_guid as @get_guid" do
        get_guid = GetGuid.create! valid_attributes
        put :update, {:id => get_guid.to_param, :get_guid => valid_attributes}, valid_session
        assigns(:get_guid).should eq(get_guid)
      end

      it "redirects to the get_guid" do
        get_guid = GetGuid.create! valid_attributes
        put :update, {:id => get_guid.to_param, :get_guid => valid_attributes}, valid_session
        response.should redirect_to(get_guid)
      end
    end

    describe "with invalid params" do
      it "assigns the get_guid as @get_guid" do
        get_guid = GetGuid.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GetGuid.any_instance.stub(:save).and_return(false)
        put :update, {:id => get_guid.to_param, :get_guid => {  }}, valid_session
        assigns(:get_guid).should eq(get_guid)
      end

      it "re-renders the 'edit' template" do
        get_guid = GetGuid.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GetGuid.any_instance.stub(:save).and_return(false)
        put :update, {:id => get_guid.to_param, :get_guid => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested get_guid" do
      get_guid = GetGuid.create! valid_attributes
      expect {
        delete :destroy, {:id => get_guid.to_param}, valid_session
      }.to change(GetGuid, :count).by(-1)
    end

    it "redirects to the get_guids list" do
      get_guid = GetGuid.create! valid_attributes
      delete :destroy, {:id => get_guid.to_param}, valid_session
      response.should redirect_to(get_guids_url)
    end
  end

end
